name: 🐛 Report a bug
description: Let us know if something's not working the way you expected.
labels: ["type:bug"]
body:
- type: markdown
  attributes:
      value: We value your time and effort to submit this bug report. 🙏
- type: textarea
  id: description
  validations:
      required: true
  attributes:
      label: "📜 Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "It bugs out when ..."

- type: textarea
  id: steps-to-reproduce
  validations:
      required: true
  attributes:
      label: "👟 Reproduction steps"
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See the error"
- type: textarea
  id: expected-behavior
  validations:
      required: true
  attributes:
      label: "👍 Expected behavior"
      description: "What did you think should happen?"
      placeholder: "It should ..."
- type: textarea
  id: actual-behavior
  validations:
      required: true
  attributes:
      label: "👎 Actual Behavior with Screenshots"
      description: "What did actually happen? Add screenshots, if applicable."
      placeholder: "It actually ..."
- type: textarea
  id: additional-context
  validations:
      required: false
  attributes:
      label: "📃 Provide any additional context for the Bug."
      description: "Add any other context about the problem here."
      placeholder: "It actually ..."
- type: checkboxes
  id: no-duplicate-issues
  attributes:
      label: "👀 Have you spent some time to check if this bug has been raised before?"
      description: Please [search the history](https://github.com/DPSN-org/dpsn-client-nodejs/issues) to see if an issue already exists for the same problem.
      options:
        - label: "I checked and didn't find a similar issue"
          required: true
- type: dropdown
  id: willing-to-submit-pr
  attributes:
      label: "Are you willing to submit PR?"
      description: "This is absolutely not required, but we are happy to guide you in the contribution process."
      options:
        - "Yes I am willing to submit a PR!"
- type: markdown
  attributes:
      value: Thank you! ❤️
